// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Message.proto

package Message

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Message_proto protoreflect.FileDescriptor

const file_Message_proto_rawDesc = "" +
	"\n" +
	"\rMessage.proto\x12\x03msg\x1a\tReq.proto22\n" +
	"\x03Msg\x12+\n" +
	"\aSendMsg\x12\x0f.req.SendMsgReq\x1a\x0f.req.DefaultResB*Z(github.com/DEEBBLUE/ExProtos/api/Messageb\x06proto3"

var file_Message_proto_goTypes = []any{
	(*Req.SendMsgReq)(nil), // 0: req.SendMsgReq
	(*Req.DefaultRes)(nil), // 1: req.DefaultRes
}
var file_Message_proto_depIdxs = []int32{
	0, // 0: msg.Msg.SendMsg:input_type -> req.SendMsgReq
	1, // 1: msg.Msg.SendMsg:output_type -> req.DefaultRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Message_proto_rawDesc), len(file_Message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
