// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Types.proto

package Types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_CLIENT Role = 0
	Role_ROLE_OPER   Role = 1
	Role_ROLE_ADMIN  Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_CLIENT",
		1: "ROLE_OPER",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_CLIENT": 0,
		"ROLE_OPER":   1,
		"ROLE_ADMIN":  2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_Types_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_Types_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{0}
}

type Verif int32

const (
	Verif_UNVERIFED  Verif = 0
	Verif_INPROCESED Verif = 1
	Verif_VERIFED    Verif = 2
)

// Enum value maps for Verif.
var (
	Verif_name = map[int32]string{
		0: "UNVERIFED",
		1: "INPROCESED",
		2: "VERIFED",
	}
	Verif_value = map[string]int32{
		"UNVERIFED":  0,
		"INPROCESED": 1,
		"VERIFED":    2,
	}
)

func (x Verif) Enum() *Verif {
	p := new(Verif)
	*p = x
	return p
}

func (x Verif) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verif) Descriptor() protoreflect.EnumDescriptor {
	return file_Types_proto_enumTypes[1].Descriptor()
}

func (Verif) Type() protoreflect.EnumType {
	return &file_Types_proto_enumTypes[1]
}

func (x Verif) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verif.Descriptor instead.
func (Verif) EnumDescriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{1}
}

type ExchangeStatus int32

const (
	ExchangeStatus_CREATED       ExchangeStatus = 0
	ExchangeStatus_EXINPROCESSED ExchangeStatus = 1
	ExchangeStatus_COMPELETED    ExchangeStatus = 2
	ExchangeStatus_CANCELED      ExchangeStatus = 3
)

// Enum value maps for ExchangeStatus.
var (
	ExchangeStatus_name = map[int32]string{
		0: "CREATED",
		1: "EXINPROCESSED",
		2: "COMPELETED",
		3: "CANCELED",
	}
	ExchangeStatus_value = map[string]int32{
		"CREATED":       0,
		"EXINPROCESSED": 1,
		"COMPELETED":    2,
		"CANCELED":      3,
	}
)

func (x ExchangeStatus) Enum() *ExchangeStatus {
	p := new(ExchangeStatus)
	*p = x
	return p
}

func (x ExchangeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_Types_proto_enumTypes[2].Descriptor()
}

func (ExchangeStatus) Type() protoreflect.EnumType {
	return &file_Types_proto_enumTypes[2]
}

func (x ExchangeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeStatus.Descriptor instead.
func (ExchangeStatus) EnumDescriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{2}
}

type ExchangeCurrency int32

const (
	ExchangeCurrency_FIAT ExchangeCurrency = 0
	ExchangeCurrency_USDT ExchangeCurrency = 1
	ExchangeCurrency_BTC  ExchangeCurrency = 2
)

// Enum value maps for ExchangeCurrency.
var (
	ExchangeCurrency_name = map[int32]string{
		0: "FIAT",
		1: "USDT",
		2: "BTC",
	}
	ExchangeCurrency_value = map[string]int32{
		"FIAT": 0,
		"USDT": 1,
		"BTC":  2,
	}
)

func (x ExchangeCurrency) Enum() *ExchangeCurrency {
	p := new(ExchangeCurrency)
	*p = x
	return p
}

func (x ExchangeCurrency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExchangeCurrency) Descriptor() protoreflect.EnumDescriptor {
	return file_Types_proto_enumTypes[3].Descriptor()
}

func (ExchangeCurrency) Type() protoreflect.EnumType {
	return &file_Types_proto_enumTypes[3]
}

func (x ExchangeCurrency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExchangeCurrency.Descriptor instead.
func (ExchangeCurrency) EnumDescriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{3}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	OwnerId       int32                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	VerifStatus   Verif                  `protobuf:"varint,3,opt,name=verif_status,json=verifStatus,proto3,enum=types.Verif" json:"verif_status,omitempty"`
	Role          Role                   `protobuf:"varint,4,opt,name=role,proto3,enum=types.Role" json:"role,omitempty"`
	Balance       int32                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_Types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_Types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *User) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *User) GetVerifStatus() Verif {
	if x != nil {
		return x.VerifStatus
	}
	return Verif_UNVERIFED
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_CLIENT
}

func (x *User) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ExchangeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      ExchangeCurrency       `protobuf:"varint,1,opt,name=currency,proto3,enum=types.ExchangeCurrency" json:"currency,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeData) Reset() {
	*x = ExchangeData{}
	mi := &file_Types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeData) ProtoMessage() {}

func (x *ExchangeData) ProtoReflect() protoreflect.Message {
	mi := &file_Types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeData.ProtoReflect.Descriptor instead.
func (*ExchangeData) Descriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeData) GetCurrency() ExchangeCurrency {
	if x != nil {
		return x.Currency
	}
	return ExchangeCurrency_FIAT
}

func (x *ExchangeData) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExchangeData) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	DataIn        *ExchangeData          `protobuf:"bytes,2,opt,name=data_in,json=dataIn,proto3" json:"data_in,omitempty"`
	DataOut       *ExchangeData          `protobuf:"bytes,3,opt,name=data_out,json=dataOut,proto3" json:"data_out,omitempty"`
	ClientId      int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperId        int32                  `protobuf:"varint,5,opt,name=oper_id,json=operId,proto3" json:"oper_id,omitempty"`
	Status        ExchangeStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=types.ExchangeStatus" json:"status,omitempty"`
	TimeStart     string                 `protobuf:"bytes,7,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd       string                 `protobuf:"bytes,8,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	Rate          float32                `protobuf:"fixed32,9,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_Types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_Types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_Types_proto_rawDescGZIP(), []int{2}
}

func (x *Exchange) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *Exchange) GetDataIn() *ExchangeData {
	if x != nil {
		return x.DataIn
	}
	return nil
}

func (x *Exchange) GetDataOut() *ExchangeData {
	if x != nil {
		return x.DataOut
	}
	return nil
}

func (x *Exchange) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Exchange) GetOperId() int32 {
	if x != nil {
		return x.OperId
	}
	return 0
}

func (x *Exchange) GetStatus() ExchangeStatus {
	if x != nil {
		return x.Status
	}
	return ExchangeStatus_CREATED
}

func (x *Exchange) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *Exchange) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *Exchange) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_Types_proto protoreflect.FileDescriptor

const file_Types_proto_rawDesc = "" +
	"\n" +
	"\vTypes.proto\x12\x05types\"\xa2\x01\n" +
	"\x04User\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x05R\aownerId\x12/\n" +
	"\fverif_status\x18\x03 \x01(\x0e2\f.types.VerifR\vverifStatus\x12\x1f\n" +
	"\x04role\x18\x04 \x01(\x0e2\v.types.RoleR\x04role\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x05R\abalance\"u\n" +
	"\fExchangeData\x123\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x17.types.ExchangeCurrencyR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\xbc\x02\n" +
	"\bExchange\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12,\n" +
	"\adata_in\x18\x02 \x01(\v2\x13.types.ExchangeDataR\x06dataIn\x12.\n" +
	"\bdata_out\x18\x03 \x01(\v2\x13.types.ExchangeDataR\adataOut\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x05R\bclientId\x12\x17\n" +
	"\aoper_id\x18\x05 \x01(\x05R\x06operId\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.types.ExchangeStatusR\x06status\x12\x1d\n" +
	"\n" +
	"time_start\x18\a \x01(\tR\ttimeStart\x12\x19\n" +
	"\btime_end\x18\b \x01(\tR\atimeEnd\x12\x12\n" +
	"\x04rate\x18\t \x01(\x02R\x04rate*6\n" +
	"\x04Role\x12\x0f\n" +
	"\vROLE_CLIENT\x10\x00\x12\r\n" +
	"\tROLE_OPER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02*3\n" +
	"\x05Verif\x12\r\n" +
	"\tUNVERIFED\x10\x00\x12\x0e\n" +
	"\n" +
	"INPROCESED\x10\x01\x12\v\n" +
	"\aVERIFED\x10\x02*N\n" +
	"\x0eExchangeStatus\x12\v\n" +
	"\aCREATED\x10\x00\x12\x11\n" +
	"\rEXINPROCESSED\x10\x01\x12\x0e\n" +
	"\n" +
	"COMPELETED\x10\x02\x12\f\n" +
	"\bCANCELED\x10\x03*/\n" +
	"\x10ExchangeCurrency\x12\b\n" +
	"\x04FIAT\x10\x00\x12\b\n" +
	"\x04USDT\x10\x01\x12\a\n" +
	"\x03BTC\x10\x02B(Z&github.com/DEEBBLUE/GoProtos/api/Typesb\x06proto3"

var (
	file_Types_proto_rawDescOnce sync.Once
	file_Types_proto_rawDescData []byte
)

func file_Types_proto_rawDescGZIP() []byte {
	file_Types_proto_rawDescOnce.Do(func() {
		file_Types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Types_proto_rawDesc), len(file_Types_proto_rawDesc)))
	})
	return file_Types_proto_rawDescData
}

var file_Types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Types_proto_goTypes = []any{
	(Role)(0),             // 0: types.Role
	(Verif)(0),            // 1: types.Verif
	(ExchangeStatus)(0),   // 2: types.ExchangeStatus
	(ExchangeCurrency)(0), // 3: types.ExchangeCurrency
	(*User)(nil),          // 4: types.User
	(*ExchangeData)(nil),  // 5: types.ExchangeData
	(*Exchange)(nil),      // 6: types.Exchange
}
var file_Types_proto_depIdxs = []int32{
	1, // 0: types.User.verif_status:type_name -> types.Verif
	0, // 1: types.User.role:type_name -> types.Role
	3, // 2: types.ExchangeData.currency:type_name -> types.ExchangeCurrency
	5, // 3: types.Exchange.data_in:type_name -> types.ExchangeData
	5, // 4: types.Exchange.data_out:type_name -> types.ExchangeData
	2, // 5: types.Exchange.status:type_name -> types.ExchangeStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Types_proto_init() }
func file_Types_proto_init() {
	if File_Types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Types_proto_rawDesc), len(file_Types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Types_proto_goTypes,
		DependencyIndexes: file_Types_proto_depIdxs,
		EnumInfos:         file_Types_proto_enumTypes,
		MessageInfos:      file_Types_proto_msgTypes,
	}.Build()
	File_Types_proto = out.File
	file_Types_proto_goTypes = nil
	file_Types_proto_depIdxs = nil
}
