// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: SpecialExchange.proto

package SpecialExchange

import (
	context "context"
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecialExchange_CreateSpecialExchange_FullMethodName = "/special_exchange.SpecialExchange/CreateSpecialExchange"
	SpecialExchange_TakeSpecialxhangeList_FullMethodName = "/special_exchange.SpecialExchange/TakeSpecialxhangeList"
	SpecialExchange_GiveSpecialDetails_FullMethodName    = "/special_exchange.SpecialExchange/GiveSpecialDetails"
	SpecialExchange_ConfirmSpecial_FullMethodName        = "/special_exchange.SpecialExchange/ConfirmSpecial"
)

// SpecialExchangeClient is the client API for SpecialExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecialExchangeClient interface {
	CreateSpecialExchange(ctx context.Context, in *Req.CreateExchangeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Req.DefaultRes], error)
	TakeSpecialxhangeList(ctx context.Context, in *Req.EmptyReq, opts ...grpc.CallOption) (*Req.RepeatListExRes, error)
	GiveSpecialDetails(ctx context.Context, in *Req.InitBankDetailExchangeReq, opts ...grpc.CallOption) (*Req.DefaultRes, error)
	ConfirmSpecial(ctx context.Context, in *Req.ConfirmReq, opts ...grpc.CallOption) (*Req.DefaultRes, error)
}

type specialExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecialExchangeClient(cc grpc.ClientConnInterface) SpecialExchangeClient {
	return &specialExchangeClient{cc}
}

func (c *specialExchangeClient) CreateSpecialExchange(ctx context.Context, in *Req.CreateExchangeReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Req.DefaultRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpecialExchange_ServiceDesc.Streams[0], SpecialExchange_CreateSpecialExchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req.CreateExchangeReq, Req.DefaultRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecialExchange_CreateSpecialExchangeClient = grpc.ServerStreamingClient[Req.DefaultRes]

func (c *specialExchangeClient) TakeSpecialxhangeList(ctx context.Context, in *Req.EmptyReq, opts ...grpc.CallOption) (*Req.RepeatListExRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Req.RepeatListExRes)
	err := c.cc.Invoke(ctx, SpecialExchange_TakeSpecialxhangeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialExchangeClient) GiveSpecialDetails(ctx context.Context, in *Req.InitBankDetailExchangeReq, opts ...grpc.CallOption) (*Req.DefaultRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Req.DefaultRes)
	err := c.cc.Invoke(ctx, SpecialExchange_GiveSpecialDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specialExchangeClient) ConfirmSpecial(ctx context.Context, in *Req.ConfirmReq, opts ...grpc.CallOption) (*Req.DefaultRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Req.DefaultRes)
	err := c.cc.Invoke(ctx, SpecialExchange_ConfirmSpecial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecialExchangeServer is the server API for SpecialExchange service.
// All implementations must embed UnimplementedSpecialExchangeServer
// for forward compatibility.
type SpecialExchangeServer interface {
	CreateSpecialExchange(*Req.CreateExchangeReq, grpc.ServerStreamingServer[Req.DefaultRes]) error
	TakeSpecialxhangeList(context.Context, *Req.EmptyReq) (*Req.RepeatListExRes, error)
	GiveSpecialDetails(context.Context, *Req.InitBankDetailExchangeReq) (*Req.DefaultRes, error)
	ConfirmSpecial(context.Context, *Req.ConfirmReq) (*Req.DefaultRes, error)
	mustEmbedUnimplementedSpecialExchangeServer()
}

// UnimplementedSpecialExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecialExchangeServer struct{}

func (UnimplementedSpecialExchangeServer) CreateSpecialExchange(*Req.CreateExchangeReq, grpc.ServerStreamingServer[Req.DefaultRes]) error {
	return status.Errorf(codes.Unimplemented, "method CreateSpecialExchange not implemented")
}
func (UnimplementedSpecialExchangeServer) TakeSpecialxhangeList(context.Context, *Req.EmptyReq) (*Req.RepeatListExRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeSpecialxhangeList not implemented")
}
func (UnimplementedSpecialExchangeServer) GiveSpecialDetails(context.Context, *Req.InitBankDetailExchangeReq) (*Req.DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveSpecialDetails not implemented")
}
func (UnimplementedSpecialExchangeServer) ConfirmSpecial(context.Context, *Req.ConfirmReq) (*Req.DefaultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmSpecial not implemented")
}
func (UnimplementedSpecialExchangeServer) mustEmbedUnimplementedSpecialExchangeServer() {}
func (UnimplementedSpecialExchangeServer) testEmbeddedByValue()                         {}

// UnsafeSpecialExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecialExchangeServer will
// result in compilation errors.
type UnsafeSpecialExchangeServer interface {
	mustEmbedUnimplementedSpecialExchangeServer()
}

func RegisterSpecialExchangeServer(s grpc.ServiceRegistrar, srv SpecialExchangeServer) {
	// If the following call pancis, it indicates UnimplementedSpecialExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecialExchange_ServiceDesc, srv)
}

func _SpecialExchange_CreateSpecialExchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Req.CreateExchangeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpecialExchangeServer).CreateSpecialExchange(m, &grpc.GenericServerStream[Req.CreateExchangeReq, Req.DefaultRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecialExchange_CreateSpecialExchangeServer = grpc.ServerStreamingServer[Req.DefaultRes]

func _SpecialExchange_TakeSpecialxhangeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req.EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialExchangeServer).TakeSpecialxhangeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialExchange_TakeSpecialxhangeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialExchangeServer).TakeSpecialxhangeList(ctx, req.(*Req.EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialExchange_GiveSpecialDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req.InitBankDetailExchangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialExchangeServer).GiveSpecialDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialExchange_GiveSpecialDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialExchangeServer).GiveSpecialDetails(ctx, req.(*Req.InitBankDetailExchangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecialExchange_ConfirmSpecial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req.ConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecialExchangeServer).ConfirmSpecial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecialExchange_ConfirmSpecial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecialExchangeServer).ConfirmSpecial(ctx, req.(*Req.ConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SpecialExchange_ServiceDesc is the grpc.ServiceDesc for SpecialExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecialExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "special_exchange.SpecialExchange",
	HandlerType: (*SpecialExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeSpecialxhangeList",
			Handler:    _SpecialExchange_TakeSpecialxhangeList_Handler,
		},
		{
			MethodName: "GiveSpecialDetails",
			Handler:    _SpecialExchange_GiveSpecialDetails_Handler,
		},
		{
			MethodName: "ConfirmSpecial",
			Handler:    _SpecialExchange_ConfirmSpecial_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSpecialExchange",
			Handler:       _SpecialExchange_CreateSpecialExchange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "SpecialExchange.proto",
}
