// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: SpecialExchange.proto

package SpecialExchange

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_SpecialExchange_proto protoreflect.FileDescriptor

const file_SpecialExchange_proto_rawDesc = "" +
	"\n" +
	"\x15SpecialExchange.proto\x12\x10special_exchange\x1a\tReq.proto2\x8e\x02\n" +
	"\x0fSpecialExchange\x12B\n" +
	"\x15CreateSpecialExchange\x12\x16.req.CreateExchangeReq\x1a\x0f.req.DefaultRes0\x01\x12<\n" +
	"\x15TakeSpecialxhangeList\x12\r.req.EmptyReq\x1a\x14.req.RepeatListExRes\x12E\n" +
	"\x12GiveSpecialDetails\x12\x1e.req.InitBankDetailExchangeReq\x1a\x0f.req.DefaultRes\x122\n" +
	"\x0eConfirmSpecial\x12\x0f.req.ConfirmReq\x1a\x0f.req.DefaultResB2Z0github.com/DEEBBLUE/ExProtos/api/SpecialExchangeb\x06proto3"

var file_SpecialExchange_proto_goTypes = []any{
	(*Req.CreateExchangeReq)(nil),         // 0: req.CreateExchangeReq
	(*Req.EmptyReq)(nil),                  // 1: req.EmptyReq
	(*Req.InitBankDetailExchangeReq)(nil), // 2: req.InitBankDetailExchangeReq
	(*Req.ConfirmReq)(nil),                // 3: req.ConfirmReq
	(*Req.DefaultRes)(nil),                // 4: req.DefaultRes
	(*Req.RepeatListExRes)(nil),           // 5: req.RepeatListExRes
}
var file_SpecialExchange_proto_depIdxs = []int32{
	0, // 0: special_exchange.SpecialExchange.CreateSpecialExchange:input_type -> req.CreateExchangeReq
	1, // 1: special_exchange.SpecialExchange.TakeSpecialxhangeList:input_type -> req.EmptyReq
	2, // 2: special_exchange.SpecialExchange.GiveSpecialDetails:input_type -> req.InitBankDetailExchangeReq
	3, // 3: special_exchange.SpecialExchange.ConfirmSpecial:input_type -> req.ConfirmReq
	4, // 4: special_exchange.SpecialExchange.CreateSpecialExchange:output_type -> req.DefaultRes
	5, // 5: special_exchange.SpecialExchange.TakeSpecialxhangeList:output_type -> req.RepeatListExRes
	4, // 6: special_exchange.SpecialExchange.GiveSpecialDetails:output_type -> req.DefaultRes
	4, // 7: special_exchange.SpecialExchange.ConfirmSpecial:output_type -> req.DefaultRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SpecialExchange_proto_init() }
func file_SpecialExchange_proto_init() {
	if File_SpecialExchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SpecialExchange_proto_rawDesc), len(file_SpecialExchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SpecialExchange_proto_goTypes,
		DependencyIndexes: file_SpecialExchange_proto_depIdxs,
	}.Build()
	File_SpecialExchange_proto = out.File
	file_SpecialExchange_proto_goTypes = nil
	file_SpecialExchange_proto_depIdxs = nil
}
