// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Stock.proto

package Stock

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Stock_proto protoreflect.FileDescriptor

const file_Stock_proto_rawDesc = "" +
	"\n" +
	"\vStock.proto\x12\x05stock\x1a\tReq.proto2C\n" +
	"\x05Stock\x12:\n" +
	"\fGetAllOrders\x12\x14.req.GetAllOrdersReq\x1a\x14.req.GetAllOrdersResB(Z&github.com/DEEBBLUE/ExProtos/api/Stockb\x06proto3"

var file_Stock_proto_goTypes = []any{
	(*Req.GetAllOrdersReq)(nil), // 0: req.GetAllOrdersReq
	(*Req.GetAllOrdersRes)(nil), // 1: req.GetAllOrdersRes
}
var file_Stock_proto_depIdxs = []int32{
	0, // 0: stock.Stock.GetAllOrders:input_type -> req.GetAllOrdersReq
	1, // 1: stock.Stock.GetAllOrders:output_type -> req.GetAllOrdersRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Stock_proto_init() }
func file_Stock_proto_init() {
	if File_Stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Stock_proto_rawDesc), len(file_Stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Stock_proto_goTypes,
		DependencyIndexes: file_Stock_proto_depIdxs,
	}.Build()
	File_Stock_proto = out.File
	file_Stock_proto_goTypes = nil
	file_Stock_proto_depIdxs = nil
}
