// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Exchange.proto

package Exchange

import (
	Req "github.com/DEEBBLUE/GoProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfirmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfirmReq) Reset() {
	*x = ClientConfirmReq{}
	mi := &file_Exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfirmReq) ProtoMessage() {}

func (x *ClientConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_Exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfirmReq.ProtoReflect.Descriptor instead.
func (*ClientConfirmReq) Descriptor() ([]byte, []int) {
	return file_Exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfirmReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

type OperConfirmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	OperId        int32                  `protobuf:"varint,2,opt,name=oper_id,json=operId,proto3" json:"oper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperConfirmReq) Reset() {
	*x = OperConfirmReq{}
	mi := &file_Exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperConfirmReq) ProtoMessage() {}

func (x *OperConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_Exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperConfirmReq.ProtoReflect.Descriptor instead.
func (*OperConfirmReq) Descriptor() ([]byte, []int) {
	return file_Exchange_proto_rawDescGZIP(), []int{1}
}

func (x *OperConfirmReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *OperConfirmReq) GetOperId() int32 {
	if x != nil {
		return x.OperId
	}
	return 0
}

var File_Exchange_proto protoreflect.FileDescriptor

const file_Exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eExchange.proto\x12\bexchange\x1a\tReq.proto\"3\n" +
	"\x10ClientConfirmReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\"J\n" +
	"\x0eOperConfirmReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12\x17\n" +
	"\aoper_id\x18\x02 \x01(\x05R\x06operId2\xc2\x02\n" +
	"\bExchange\x12<\n" +
	"\x11CreateNewExchange\x12\x16.req.CreateExchangeReq\x1a\x0f.req.DefaultRes\x12@\n" +
	"\x0eTakeNewExhange\x12\x16.req.RepeatExchangeReq\x1a\x16.req.RepeatExchangeRes\x12>\n" +
	"\vGiveDetails\x12\x1e.req.InitBankDetailExchangeReq\x1a\x0f.req.DefaultRes\x12<\n" +
	"\rClientConfirm\x12\x1a.exchange.ClientConfirmReq\x1a\x0f.req.DefaultRes\x128\n" +
	"\vOperConfirm\x12\x18.exchange.OperConfirmReq\x1a\x0f.req.DefaultResB+Z)github.com/DEEBBLUE/GoProtos/api/Exchangeb\x06proto3"

var (
	file_Exchange_proto_rawDescOnce sync.Once
	file_Exchange_proto_rawDescData []byte
)

func file_Exchange_proto_rawDescGZIP() []byte {
	file_Exchange_proto_rawDescOnce.Do(func() {
		file_Exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Exchange_proto_rawDesc), len(file_Exchange_proto_rawDesc)))
	})
	return file_Exchange_proto_rawDescData
}

var file_Exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Exchange_proto_goTypes = []any{
	(*ClientConfirmReq)(nil),              // 0: exchange.ClientConfirmReq
	(*OperConfirmReq)(nil),                // 1: exchange.OperConfirmReq
	(*Req.CreateExchangeReq)(nil),         // 2: req.CreateExchangeReq
	(*Req.RepeatExchangeReq)(nil),         // 3: req.RepeatExchangeReq
	(*Req.InitBankDetailExchangeReq)(nil), // 4: req.InitBankDetailExchangeReq
	(*Req.DefaultRes)(nil),                // 5: req.DefaultRes
	(*Req.RepeatExchangeRes)(nil),         // 6: req.RepeatExchangeRes
}
var file_Exchange_proto_depIdxs = []int32{
	2, // 0: exchange.Exchange.CreateNewExchange:input_type -> req.CreateExchangeReq
	3, // 1: exchange.Exchange.TakeNewExhange:input_type -> req.RepeatExchangeReq
	4, // 2: exchange.Exchange.GiveDetails:input_type -> req.InitBankDetailExchangeReq
	0, // 3: exchange.Exchange.ClientConfirm:input_type -> exchange.ClientConfirmReq
	1, // 4: exchange.Exchange.OperConfirm:input_type -> exchange.OperConfirmReq
	5, // 5: exchange.Exchange.CreateNewExchange:output_type -> req.DefaultRes
	6, // 6: exchange.Exchange.TakeNewExhange:output_type -> req.RepeatExchangeRes
	5, // 7: exchange.Exchange.GiveDetails:output_type -> req.DefaultRes
	5, // 8: exchange.Exchange.ClientConfirm:output_type -> req.DefaultRes
	5, // 9: exchange.Exchange.OperConfirm:output_type -> req.DefaultRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Exchange_proto_init() }
func file_Exchange_proto_init() {
	if File_Exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Exchange_proto_rawDesc), len(file_Exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Exchange_proto_goTypes,
		DependencyIndexes: file_Exchange_proto_depIdxs,
		MessageInfos:      file_Exchange_proto_msgTypes,
	}.Build()
	File_Exchange_proto = out.File
	file_Exchange_proto_goTypes = nil
	file_Exchange_proto_depIdxs = nil
}
