// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RCExchange.proto

package Exchange

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_RCExchange_proto protoreflect.FileDescriptor

const file_RCExchange_proto_rawDesc = "" +
	"\n" +
	"\x10RCExchange.proto\x12\bexchange\x1a\tReq.proto2\xf0\x01\n" +
	"\n" +
	"CRExchange\x12;\n" +
	"\x10CreateRCExchange\x12\x16.req.CreateExchangeReq\x1a\x0f.req.DefaultRes\x128\n" +
	"\x11TakeRCExhangeList\x12\r.req.EmptyReq\x1a\x14.req.RepeatListExRes\x12>\n" +
	"\vGiveDetails\x12\x1e.req.InitBankDetailExchangeReq\x1a\x0f.req.DefaultRes\x12+\n" +
	"\aConfirm\x12\x0f.req.ConfirmReq\x1a\x0f.req.DefaultResB+Z)github.com/DEEBBLUE/ExProtos/api/Exchangeb\x06proto3"

var file_RCExchange_proto_goTypes = []any{
	(*Req.CreateExchangeReq)(nil),         // 0: req.CreateExchangeReq
	(*Req.EmptyReq)(nil),                  // 1: req.EmptyReq
	(*Req.InitBankDetailExchangeReq)(nil), // 2: req.InitBankDetailExchangeReq
	(*Req.ConfirmReq)(nil),                // 3: req.ConfirmReq
	(*Req.DefaultRes)(nil),                // 4: req.DefaultRes
	(*Req.RepeatListExRes)(nil),           // 5: req.RepeatListExRes
}
var file_RCExchange_proto_depIdxs = []int32{
	0, // 0: exchange.CRExchange.CreateRCExchange:input_type -> req.CreateExchangeReq
	1, // 1: exchange.CRExchange.TakeRCExhangeList:input_type -> req.EmptyReq
	2, // 2: exchange.CRExchange.GiveDetails:input_type -> req.InitBankDetailExchangeReq
	3, // 3: exchange.CRExchange.Confirm:input_type -> req.ConfirmReq
	4, // 4: exchange.CRExchange.CreateRCExchange:output_type -> req.DefaultRes
	5, // 5: exchange.CRExchange.TakeRCExhangeList:output_type -> req.RepeatListExRes
	4, // 6: exchange.CRExchange.GiveDetails:output_type -> req.DefaultRes
	4, // 7: exchange.CRExchange.Confirm:output_type -> req.DefaultRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RCExchange_proto_init() }
func file_RCExchange_proto_init() {
	if File_RCExchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RCExchange_proto_rawDesc), len(file_RCExchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RCExchange_proto_goTypes,
		DependencyIndexes: file_RCExchange_proto_depIdxs,
	}.Build()
	File_RCExchange_proto = out.File
	file_RCExchange_proto_goTypes = nil
	file_RCExchange_proto_depIdxs = nil
}
