// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefsreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TgId          int32                  `protobuf:"varint,2,opt,name=tgId,proto3" json:"tgId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefsreshReq) Reset() {
	*x = RefsreshReq{}
	mi := &file_Auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefsreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefsreshReq) ProtoMessage() {}

func (x *RefsreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_Auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefsreshReq.ProtoReflect.Descriptor instead.
func (*RefsreshReq) Descriptor() ([]byte, []int) {
	return file_Auth_proto_rawDescGZIP(), []int{0}
}

func (x *RefsreshReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefsreshReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type RefsreshRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefsreshRes) Reset() {
	*x = RefsreshRes{}
	mi := &file_Auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefsreshRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefsreshRes) ProtoMessage() {}

func (x *RefsreshRes) ProtoReflect() protoreflect.Message {
	mi := &file_Auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefsreshRes.ProtoReflect.Descriptor instead.
func (*RefsreshRes) Descriptor() ([]byte, []int) {
	return file_Auth_proto_rawDescGZIP(), []int{1}
}

func (x *RefsreshRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessReq) Reset() {
	*x = AccessReq{}
	mi := &file_Auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessReq) ProtoMessage() {}

func (x *AccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_Auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessReq.ProtoReflect.Descriptor instead.
func (*AccessReq) Descriptor() ([]byte, []int) {
	return file_Auth_proto_rawDescGZIP(), []int{2}
}

func (x *AccessReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRes) Reset() {
	*x = AccessRes{}
	mi := &file_Auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRes) ProtoMessage() {}

func (x *AccessRes) ProtoReflect() protoreflect.Message {
	mi := &file_Auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRes.ProtoReflect.Descriptor instead.
func (*AccessRes) Descriptor() ([]byte, []int) {
	return file_Auth_proto_rawDescGZIP(), []int{3}
}

func (x *AccessRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_Auth_proto protoreflect.FileDescriptor

const file_Auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Auth.proto\x12\x04auth\"7\n" +
	"\vRefsreshReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04tgId\x18\x02 \x01(\x05R\x04tgId\"/\n" +
	"\vRefsreshRes\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"-\n" +
	"\tAccessReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"#\n" +
	"\tAccessRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2c\n" +
	"\x04Auth\x12/\n" +
	"\aRefresh\x12\x11.auth.RefsreshReq\x1a\x11.auth.RefsreshRes\x12*\n" +
	"\x06Access\x12\x0f.auth.AccessReq\x1a\x0f.auth.AccessResB\aZ\x05auth/b\x06proto3"

var (
	file_Auth_proto_rawDescOnce sync.Once
	file_Auth_proto_rawDescData []byte
)

func file_Auth_proto_rawDescGZIP() []byte {
	file_Auth_proto_rawDescOnce.Do(func() {
		file_Auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Auth_proto_rawDesc), len(file_Auth_proto_rawDesc)))
	})
	return file_Auth_proto_rawDescData
}

var file_Auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Auth_proto_goTypes = []any{
	(*RefsreshReq)(nil), // 0: auth.RefsreshReq
	(*RefsreshRes)(nil), // 1: auth.RefsreshRes
	(*AccessReq)(nil),   // 2: auth.AccessReq
	(*AccessRes)(nil),   // 3: auth.AccessRes
}
var file_Auth_proto_depIdxs = []int32{
	0, // 0: auth.Auth.Refresh:input_type -> auth.RefsreshReq
	2, // 1: auth.Auth.Access:input_type -> auth.AccessReq
	1, // 2: auth.Auth.Refresh:output_type -> auth.RefsreshRes
	3, // 3: auth.Auth.Access:output_type -> auth.AccessRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Auth_proto_init() }
func file_Auth_proto_init() {
	if File_Auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Auth_proto_rawDesc), len(file_Auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Auth_proto_goTypes,
		DependencyIndexes: file_Auth_proto_depIdxs,
		MessageInfos:      file_Auth_proto_msgTypes,
	}.Build()
	File_Auth_proto = out.File
	file_Auth_proto_goTypes = nil
	file_Auth_proto_depIdxs = nil
}
