// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Sso.proto

package Sso

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Sso_proto protoreflect.FileDescriptor

const file_Sso_proto_rawDesc = "" +
	"\n" +
	"\tSso.proto\x12\x03sso\x1a\tReq.proto2\x8b\x01\n" +
	"\x03Sso\x12)\n" +
	"\x06Access\x12\x0e.req.AccessReq\x1a\x0f.req.DefaultRes\x12+\n" +
	"\aRefresh\x12\x0f.req.RefreshReq\x1a\x0f.req.RefreshRes\x12,\n" +
	"\vRoleConfirm\x12\f.req.RoleReq\x1a\x0f.req.DefaultResB&Z$github.com/DEEBBLUE/ExProtos/api/Ssob\x06proto3"

var file_Sso_proto_goTypes = []any{
	(*Req.AccessReq)(nil),  // 0: req.AccessReq
	(*Req.RefreshReq)(nil), // 1: req.RefreshReq
	(*Req.RoleReq)(nil),    // 2: req.RoleReq
	(*Req.DefaultRes)(nil), // 3: req.DefaultRes
	(*Req.RefreshRes)(nil), // 4: req.RefreshRes
}
var file_Sso_proto_depIdxs = []int32{
	0, // 0: sso.Sso.Access:input_type -> req.AccessReq
	1, // 1: sso.Sso.Refresh:input_type -> req.RefreshReq
	2, // 2: sso.Sso.RoleConfirm:input_type -> req.RoleReq
	3, // 3: sso.Sso.Access:output_type -> req.DefaultRes
	4, // 4: sso.Sso.Refresh:output_type -> req.RefreshRes
	3, // 5: sso.Sso.RoleConfirm:output_type -> req.DefaultRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Sso_proto_init() }
func file_Sso_proto_init() {
	if File_Sso_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Sso_proto_rawDesc), len(file_Sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Sso_proto_goTypes,
		DependencyIndexes: file_Sso_proto_depIdxs,
	}.Build()
	File_Sso_proto = out.File
	file_Sso_proto_goTypes = nil
	file_Sso_proto_depIdxs = nil
}
