// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Req.proto

package Req

import (
	Types "github.com/DEEBBLUE/ExProtos/api/Types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultRes) Reset() {
	*x = DefaultRes{}
	mi := &file_Req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRes) ProtoMessage() {}

func (x *DefaultRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRes.ProtoReflect.Descriptor instead.
func (*DefaultRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DataIn        *Types.ExchangeData    `protobuf:"bytes,2,opt,name=data_in,json=dataIn,proto3" json:"data_in,omitempty"`
	DataOut       *Types.ExchangeData    `protobuf:"bytes,3,opt,name=data_out,json=dataOut,proto3" json:"data_out,omitempty"`
	Rate          float32                `protobuf:"fixed32,4,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeReq) Reset() {
	*x = CreateExchangeReq{}
	mi := &file_Req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeReq) ProtoMessage() {}

func (x *CreateExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeReq.ProtoReflect.Descriptor instead.
func (*CreateExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExchangeReq) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateExchangeReq) GetDataIn() *Types.ExchangeData {
	if x != nil {
		return x.DataIn
	}
	return nil
}

func (x *CreateExchangeReq) GetDataOut() *Types.ExchangeData {
	if x != nil {
		return x.DataOut
	}
	return nil
}

func (x *CreateExchangeReq) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type RepeatExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatExchangeReq) Reset() {
	*x = RepeatExchangeReq{}
	mi := &file_Req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatExchangeReq) ProtoMessage() {}

func (x *RepeatExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatExchangeReq.ProtoReflect.Descriptor instead.
func (*RepeatExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

type RepeatExchangeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Exchange      *Types.Exchange        `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatExchangeRes) Reset() {
	*x = RepeatExchangeRes{}
	mi := &file_Req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatExchangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatExchangeRes) ProtoMessage() {}

func (x *RepeatExchangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatExchangeRes.ProtoReflect.Descriptor instead.
func (*RepeatExchangeRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatExchangeRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RepeatExchangeRes) GetExchange() *Types.Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type InitOperExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	OperId        int32                  `protobuf:"varint,2,opt,name=oper_id,json=operId,proto3" json:"oper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOperExchangeReq) Reset() {
	*x = InitOperExchangeReq{}
	mi := &file_Req_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOperExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOperExchangeReq) ProtoMessage() {}

func (x *InitOperExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOperExchangeReq.ProtoReflect.Descriptor instead.
func (*InitOperExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{4}
}

func (x *InitOperExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *InitOperExchangeReq) GetOperId() int32 {
	if x != nil {
		return x.OperId
	}
	return 0
}

type InitBankDetailExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	BankDetail    string                 `protobuf:"bytes,2,opt,name=bank_detail,json=bankDetail,proto3" json:"bank_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBankDetailExchangeReq) Reset() {
	*x = InitBankDetailExchangeReq{}
	mi := &file_Req_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBankDetailExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBankDetailExchangeReq) ProtoMessage() {}

func (x *InitBankDetailExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBankDetailExchangeReq.ProtoReflect.Descriptor instead.
func (*InitBankDetailExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{5}
}

func (x *InitBankDetailExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *InitBankDetailExchangeReq) GetBankDetail() string {
	if x != nil {
		return x.BankDetail
	}
	return ""
}

type ChangeStatusExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	NewStatus     Types.ExchangeStatus   `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=types.ExchangeStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusExchangeReq) Reset() {
	*x = ChangeStatusExchangeReq{}
	mi := &file_Req_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusExchangeReq) ProtoMessage() {}

func (x *ChangeStatusExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusExchangeReq.ProtoReflect.Descriptor instead.
func (*ChangeStatusExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeStatusExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *ChangeStatusExchangeReq) GetNewStatus() Types.ExchangeStatus {
	if x != nil {
		return x.NewStatus
	}
	return Types.ExchangeStatus(0)
}

type RepeatUserHistoryReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to AmountChanges:
	//
	//	*RepeatUserHistoryReq_Count
	//	*RepeatUserHistoryReq_Full
	AmountChanges isRepeatUserHistoryReq_AmountChanges `protobuf_oneof:"amount_changes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatUserHistoryReq) Reset() {
	*x = RepeatUserHistoryReq{}
	mi := &file_Req_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatUserHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatUserHistoryReq) ProtoMessage() {}

func (x *RepeatUserHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatUserHistoryReq.ProtoReflect.Descriptor instead.
func (*RepeatUserHistoryReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{7}
}

func (x *RepeatUserHistoryReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RepeatUserHistoryReq) GetAmountChanges() isRepeatUserHistoryReq_AmountChanges {
	if x != nil {
		return x.AmountChanges
	}
	return nil
}

func (x *RepeatUserHistoryReq) GetCount() int32 {
	if x != nil {
		if x, ok := x.AmountChanges.(*RepeatUserHistoryReq_Count); ok {
			return x.Count
		}
	}
	return 0
}

func (x *RepeatUserHistoryReq) GetFull() string {
	if x != nil {
		if x, ok := x.AmountChanges.(*RepeatUserHistoryReq_Full); ok {
			return x.Full
		}
	}
	return ""
}

type isRepeatUserHistoryReq_AmountChanges interface {
	isRepeatUserHistoryReq_AmountChanges()
}

type RepeatUserHistoryReq_Count struct {
	Count int32 `protobuf:"varint,2,opt,name=count,proto3,oneof"`
}

type RepeatUserHistoryReq_Full struct {
	Full string `protobuf:"bytes,3,opt,name=full,proto3,oneof"`
}

func (*RepeatUserHistoryReq_Count) isRepeatUserHistoryReq_AmountChanges() {}

func (*RepeatUserHistoryReq_Full) isRepeatUserHistoryReq_AmountChanges() {}

type RepeatUserHistoryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryList   []*Types.Exchange      `protobuf:"bytes,1,rep,name=history_list,json=historyList,proto3" json:"history_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatUserHistoryRes) Reset() {
	*x = RepeatUserHistoryRes{}
	mi := &file_Req_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatUserHistoryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatUserHistoryRes) ProtoMessage() {}

func (x *RepeatUserHistoryRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatUserHistoryRes.ProtoReflect.Descriptor instead.
func (*RepeatUserHistoryRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{8}
}

func (x *RepeatUserHistoryRes) GetHistoryList() []*Types.Exchange {
	if x != nil {
		return x.HistoryList
	}
	return nil
}

var File_Req_proto protoreflect.FileDescriptor

const file_Req_proto_rawDesc = "" +
	"\n" +
	"\tReq.proto\x12\x03req\x1a\vTypes.proto\"$\n" +
	"\n" +
	"DefaultRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xa2\x01\n" +
	"\x11CreateExchangeReq\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12,\n" +
	"\adata_in\x18\x02 \x01(\v2\x13.types.ExchangeDataR\x06dataIn\x12.\n" +
	"\bdata_out\x18\x03 \x01(\v2\x13.types.ExchangeDataR\adataOut\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x02R\x04rate\"4\n" +
	"\x11RepeatExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\"X\n" +
	"\x11RepeatExchangeRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12+\n" +
	"\bexchange\x18\x02 \x01(\v2\x0f.types.ExchangeR\bexchange\"O\n" +
	"\x13InitOperExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12\x17\n" +
	"\aoper_id\x18\x02 \x01(\x05R\x06operId\"]\n" +
	"\x19InitBankDetailExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12\x1f\n" +
	"\vbank_detail\x18\x02 \x01(\tR\n" +
	"bankDetail\"p\n" +
	"\x17ChangeStatusExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.types.ExchangeStatusR\tnewStatus\"o\n" +
	"\x14RepeatUserHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x05count\x18\x02 \x01(\x05H\x00R\x05count\x12\x14\n" +
	"\x04full\x18\x03 \x01(\tH\x00R\x04fullB\x10\n" +
	"\x0eamount_changes\"J\n" +
	"\x14RepeatUserHistoryRes\x122\n" +
	"\fhistory_list\x18\x01 \x03(\v2\x0f.types.ExchangeR\vhistoryListB&Z$github.com/DEEBBLUE/ExProtos/api/Reqb\x06proto3"

var (
	file_Req_proto_rawDescOnce sync.Once
	file_Req_proto_rawDescData []byte
)

func file_Req_proto_rawDescGZIP() []byte {
	file_Req_proto_rawDescOnce.Do(func() {
		file_Req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)))
	})
	return file_Req_proto_rawDescData
}

var file_Req_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Req_proto_goTypes = []any{
	(*DefaultRes)(nil),                // 0: req.DefaultRes
	(*CreateExchangeReq)(nil),         // 1: req.CreateExchangeReq
	(*RepeatExchangeReq)(nil),         // 2: req.RepeatExchangeReq
	(*RepeatExchangeRes)(nil),         // 3: req.RepeatExchangeRes
	(*InitOperExchangeReq)(nil),       // 4: req.InitOperExchangeReq
	(*InitBankDetailExchangeReq)(nil), // 5: req.InitBankDetailExchangeReq
	(*ChangeStatusExchangeReq)(nil),   // 6: req.ChangeStatusExchangeReq
	(*RepeatUserHistoryReq)(nil),      // 7: req.RepeatUserHistoryReq
	(*RepeatUserHistoryRes)(nil),      // 8: req.RepeatUserHistoryRes
	(*Types.ExchangeData)(nil),        // 9: types.ExchangeData
	(*Types.Exchange)(nil),            // 10: types.Exchange
	(Types.ExchangeStatus)(0),         // 11: types.ExchangeStatus
}
var file_Req_proto_depIdxs = []int32{
	9,  // 0: req.CreateExchangeReq.data_in:type_name -> types.ExchangeData
	9,  // 1: req.CreateExchangeReq.data_out:type_name -> types.ExchangeData
	10, // 2: req.RepeatExchangeRes.exchange:type_name -> types.Exchange
	11, // 3: req.ChangeStatusExchangeReq.new_status:type_name -> types.ExchangeStatus
	10, // 4: req.RepeatUserHistoryRes.history_list:type_name -> types.Exchange
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_Req_proto_init() }
func file_Req_proto_init() {
	if File_Req_proto != nil {
		return
	}
	file_Req_proto_msgTypes[7].OneofWrappers = []any{
		(*RepeatUserHistoryReq_Count)(nil),
		(*RepeatUserHistoryReq_Full)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Req_proto_goTypes,
		DependencyIndexes: file_Req_proto_depIdxs,
		MessageInfos:      file_Req_proto_msgTypes,
	}.Build()
	File_Req_proto = out.File
	file_Req_proto_goTypes = nil
	file_Req_proto_depIdxs = nil
}
