// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Req.proto

package Req

import (
	Types "github.com/DEEBBLUE/ExProtos/api/Types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultRes) Reset() {
	*x = DefaultRes{}
	mi := &file_Req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRes) ProtoMessage() {}

func (x *DefaultRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRes.ProtoReflect.Descriptor instead.
func (*DefaultRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_Req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{1}
}

// User
type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Owner         int32                  `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ChatId        int32                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_Req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *CreateUserReq) GetOwner() int32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *CreateUserReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type RepeatUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatUserReq) Reset() {
	*x = RepeatUserReq{}
	mi := &file_Req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatUserReq) ProtoMessage() {}

func (x *RepeatUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatUserReq.ProtoReflect.Descriptor instead.
func (*RepeatUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatUserReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type RepeatUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *Types.User            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatUserRes) Reset() {
	*x = RepeatUserRes{}
	mi := &file_Req_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatUserRes) ProtoMessage() {}

func (x *RepeatUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatUserRes.ProtoReflect.Descriptor instead.
func (*RepeatUserRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{4}
}

func (x *RepeatUserRes) GetUser() *Types.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeRoleUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	NewRole       Types.Role             `protobuf:"varint,2,opt,name=new_role,json=newRole,proto3,enum=types.Role" json:"new_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRoleUserReq) Reset() {
	*x = ChangeRoleUserReq{}
	mi := &file_Req_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRoleUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoleUserReq) ProtoMessage() {}

func (x *ChangeRoleUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoleUserReq.ProtoReflect.Descriptor instead.
func (*ChangeRoleUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeRoleUserReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *ChangeRoleUserReq) GetNewRole() Types.Role {
	if x != nil {
		return x.NewRole
	}
	return Types.Role(0)
}

type ChangeVerifeStatusUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	NewVerif      Types.Verif            `protobuf:"varint,2,opt,name=new_verif,json=newVerif,proto3,enum=types.Verif" json:"new_verif,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeVerifeStatusUserReq) Reset() {
	*x = ChangeVerifeStatusUserReq{}
	mi := &file_Req_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeVerifeStatusUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeVerifeStatusUserReq) ProtoMessage() {}

func (x *ChangeVerifeStatusUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeVerifeStatusUserReq.ProtoReflect.Descriptor instead.
func (*ChangeVerifeStatusUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeVerifeStatusUserReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *ChangeVerifeStatusUserReq) GetNewVerif() Types.Verif {
	if x != nil {
		return x.NewVerif
	}
	return Types.Verif(0)
}

type ChangeBalanceUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	NewBalance    int32                  `protobuf:"varint,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBalanceUserReq) Reset() {
	*x = ChangeBalanceUserReq{}
	mi := &file_Req_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBalanceUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBalanceUserReq) ProtoMessage() {}

func (x *ChangeBalanceUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBalanceUserReq.ProtoReflect.Descriptor instead.
func (*ChangeBalanceUserReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeBalanceUserReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *ChangeBalanceUserReq) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

// Exchange
type CreateExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *Types.Exchange        `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeReq) Reset() {
	*x = CreateExchangeReq{}
	mi := &file_Req_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeReq) ProtoMessage() {}

func (x *CreateExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeReq.ProtoReflect.Descriptor instead.
func (*CreateExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{8}
}

func (x *CreateExchangeReq) GetExchange() *Types.Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type CreateExchangeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExId          int32                  `protobuf:"varint,1,opt,name=ExId,proto3" json:"ExId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeRes) Reset() {
	*x = CreateExchangeRes{}
	mi := &file_Req_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRes) ProtoMessage() {}

func (x *CreateExchangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRes.ProtoReflect.Descriptor instead.
func (*CreateExchangeRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{9}
}

func (x *CreateExchangeRes) GetExId() int32 {
	if x != nil {
		return x.ExId
	}
	return 0
}

type RepeatExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatExchangeReq) Reset() {
	*x = RepeatExchangeReq{}
	mi := &file_Req_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatExchangeReq) ProtoMessage() {}

func (x *RepeatExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatExchangeReq.ProtoReflect.Descriptor instead.
func (*RepeatExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{10}
}

func (x *RepeatExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

type RepeatExchangeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *Types.Exchange        `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatExchangeRes) Reset() {
	*x = RepeatExchangeRes{}
	mi := &file_Req_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatExchangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatExchangeRes) ProtoMessage() {}

func (x *RepeatExchangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatExchangeRes.ProtoReflect.Descriptor instead.
func (*RepeatExchangeRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{11}
}

func (x *RepeatExchangeRes) GetExchange() *Types.Exchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type InitBankDetailExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	BankDetail    string                 `protobuf:"bytes,2,opt,name=bank_detail,json=bankDetail,proto3" json:"bank_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitBankDetailExchangeReq) Reset() {
	*x = InitBankDetailExchangeReq{}
	mi := &file_Req_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitBankDetailExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBankDetailExchangeReq) ProtoMessage() {}

func (x *InitBankDetailExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBankDetailExchangeReq.ProtoReflect.Descriptor instead.
func (*InitBankDetailExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{12}
}

func (x *InitBankDetailExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *InitBankDetailExchangeReq) GetBankDetail() string {
	if x != nil {
		return x.BankDetail
	}
	return ""
}

type ConfirmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReq) Reset() {
	*x = ConfirmReq{}
	mi := &file_Req_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReq) ProtoMessage() {}

func (x *ConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReq.ProtoReflect.Descriptor instead.
func (*ConfirmReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

// User History
type RepeatUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatUserListReq) Reset() {
	*x = RepeatUserListReq{}
	mi := &file_Req_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatUserListReq) ProtoMessage() {}

func (x *RepeatUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatUserListReq.ProtoReflect.Descriptor instead.
func (*RepeatUserListReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{14}
}

func (x *RepeatUserListReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RepeatUserListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type RepeatListExRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryList   []*Types.Exchange      `protobuf:"bytes,1,rep,name=history_list,json=historyList,proto3" json:"history_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatListExRes) Reset() {
	*x = RepeatListExRes{}
	mi := &file_Req_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatListExRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatListExRes) ProtoMessage() {}

func (x *RepeatListExRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatListExRes.ProtoReflect.Descriptor instead.
func (*RepeatListExRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{15}
}

func (x *RepeatListExRes) GetHistoryList() []*Types.Exchange {
	if x != nil {
		return x.HistoryList
	}
	return nil
}

// SSO
type AccessReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessReq) Reset() {
	*x = AccessReq{}
	mi := &file_Req_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessReq) ProtoMessage() {}

func (x *AccessReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessReq.ProtoReflect.Descriptor instead.
func (*AccessReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{16}
}

func (x *AccessReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int32                  `protobuf:"varint,1,opt,name=TgId,proto3" json:"TgId,omitempty"`
	ChatId        int32                  `protobuf:"varint,2,opt,name=ChatId,proto3" json:"ChatId,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshReq) Reset() {
	*x = RefreshReq{}
	mi := &file_Req_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshReq) ProtoMessage() {}

func (x *RefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshReq.ProtoReflect.Descriptor instead.
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshReq) GetTgId() int32 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *RefreshReq) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *RefreshReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRes) Reset() {
	*x = RefreshRes{}
	mi := &file_Req_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRes) ProtoMessage() {}

func (x *RefreshRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRes.ProtoReflect.Descriptor instead.
func (*RefreshRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Types.Role             `protobuf:"varint,1,opt,name=role,proto3,enum=types.Role" json:"role,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleReq) Reset() {
	*x = RoleReq{}
	mi := &file_Req_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleReq) ProtoMessage() {}

func (x *RoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleReq.ProtoReflect.Descriptor instead.
func (*RoleReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{19}
}

func (x *RoleReq) GetRole() Types.Role {
	if x != nil {
		return x.Role
	}
	return Types.Role(0)
}

func (x *RoleReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// Messages
type SendMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublisherId   int32                  `protobuf:"varint,1,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	ConsumerId    int32                  `protobuf:"varint,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	mi := &file_Req_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{20}
}

func (x *SendMsgReq) GetPublisherId() int32 {
	if x != nil {
		return x.PublisherId
	}
	return 0
}

func (x *SendMsgReq) GetConsumerId() int32 {
	if x != nil {
		return x.ConsumerId
	}
	return 0
}

func (x *SendMsgReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Rate
type GetRateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyIn    Types.ExchangeCurrency `protobuf:"varint,1,opt,name=currency_in,json=currencyIn,proto3,enum=types.ExchangeCurrency" json:"currency_in,omitempty"`
	CurrencyOut   Types.ExchangeCurrency `protobuf:"varint,2,opt,name=currency_out,json=currencyOut,proto3,enum=types.ExchangeCurrency" json:"currency_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateReq) Reset() {
	*x = GetRateReq{}
	mi := &file_Req_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateReq) ProtoMessage() {}

func (x *GetRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateReq.ProtoReflect.Descriptor instead.
func (*GetRateReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{21}
}

func (x *GetRateReq) GetCurrencyIn() Types.ExchangeCurrency {
	if x != nil {
		return x.CurrencyIn
	}
	return Types.ExchangeCurrency(0)
}

func (x *GetRateReq) GetCurrencyOut() Types.ExchangeCurrency {
	if x != nil {
		return x.CurrencyOut
	}
	return Types.ExchangeCurrency(0)
}

type GetRateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float32                `protobuf:"fixed32,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRes) Reset() {
	*x = GetRateRes{}
	mi := &file_Req_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRes) ProtoMessage() {}

func (x *GetRateRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRes.ProtoReflect.Descriptor instead.
func (*GetRateRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{22}
}

func (x *GetRateRes) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// Stock
type GetAllOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyIn    Types.ExchangeCurrency `protobuf:"varint,1,opt,name=currency_in,json=currencyIn,proto3,enum=types.ExchangeCurrency" json:"currency_in,omitempty"`
	CurrencyOut   Types.ExchangeCurrency `protobuf:"varint,2,opt,name=currency_out,json=currencyOut,proto3,enum=types.ExchangeCurrency" json:"currency_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersReq) Reset() {
	*x = GetAllOrdersReq{}
	mi := &file_Req_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersReq) ProtoMessage() {}

func (x *GetAllOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersReq.ProtoReflect.Descriptor instead.
func (*GetAllOrdersReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{23}
}

func (x *GetAllOrdersReq) GetCurrencyIn() Types.ExchangeCurrency {
	if x != nil {
		return x.CurrencyIn
	}
	return Types.ExchangeCurrency(0)
}

func (x *GetAllOrdersReq) GetCurrencyOut() Types.ExchangeCurrency {
	if x != nil {
		return x.CurrencyOut
	}
	return Types.ExchangeCurrency(0)
}

type GetAllOrdersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Types.Order         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersRes) Reset() {
	*x = GetAllOrdersRes{}
	mi := &file_Req_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersRes) ProtoMessage() {}

func (x *GetAllOrdersRes) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersRes.ProtoReflect.Descriptor instead.
func (*GetAllOrdersRes) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{24}
}

func (x *GetAllOrdersRes) GetOrders() []*Types.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Conf
type AddExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      Types.ExchangeCurrency `protobuf:"varint,3,opt,name=currency,proto3,enum=types.ExchangeCurrency" json:"currency,omitempty"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExchangeReq) Reset() {
	*x = AddExchangeReq{}
	mi := &file_Req_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExchangeReq) ProtoMessage() {}

func (x *AddExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_Req_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExchangeReq.ProtoReflect.Descriptor instead.
func (*AddExchangeReq) Descriptor() ([]byte, []int) {
	return file_Req_proto_rawDescGZIP(), []int{25}
}

func (x *AddExchangeReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *AddExchangeReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddExchangeReq) GetCurrency() Types.ExchangeCurrency {
	if x != nil {
		return x.Currency
	}
	return Types.ExchangeCurrency(0)
}

func (x *AddExchangeReq) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

var File_Req_proto protoreflect.FileDescriptor

const file_Req_proto_rawDesc = "" +
	"\n" +
	"\tReq.proto\x12\x03req\x1a\vTypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\n" +
	"DefaultRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\n" +
	"\n" +
	"\bEmptyReq\"S\n" +
	"\rCreateUserReq\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\x05R\x05owner\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x05R\x06chatId\"$\n" +
	"\rRepeatUserReq\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\"0\n" +
	"\rRepeatUserRes\x12\x1f\n" +
	"\x04user\x18\x02 \x01(\v2\v.types.UserR\x04user\"P\n" +
	"\x11ChangeRoleUserReq\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\x12&\n" +
	"\bnew_role\x18\x02 \x01(\x0e2\v.types.RoleR\anewRole\"[\n" +
	"\x19ChangeVerifeStatusUserReq\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\x12)\n" +
	"\tnew_verif\x18\x02 \x01(\x0e2\f.types.VerifR\bnewVerif\"L\n" +
	"\x14ChangeBalanceUserReq\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x05R\x04tgId\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\x05R\n" +
	"newBalance\"@\n" +
	"\x11CreateExchangeReq\x12+\n" +
	"\bexchange\x18\x01 \x01(\v2\x0f.types.ExchangeR\bexchange\"'\n" +
	"\x11CreateExchangeRes\x12\x12\n" +
	"\x04ExId\x18\x01 \x01(\x05R\x04ExId\"4\n" +
	"\x11RepeatExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\"@\n" +
	"\x11RepeatExchangeRes\x12+\n" +
	"\bexchange\x18\x02 \x01(\v2\x0f.types.ExchangeR\bexchange\"]\n" +
	"\x19InitBankDetailExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12\x1f\n" +
	"\vbank_detail\x18\x02 \x01(\tR\n" +
	"bankDetail\"-\n" +
	"\n" +
	"ConfirmReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\"@\n" +
	"\x11RepeatUserListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"E\n" +
	"\x0fRepeatListExRes\x122\n" +
	"\fhistory_list\x18\x01 \x03(\v2\x0f.types.ExchangeR\vhistoryList\"-\n" +
	"\tAccessReq\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\"N\n" +
	"\n" +
	"RefreshReq\x12\x12\n" +
	"\x04TgId\x18\x01 \x01(\x05R\x04TgId\x12\x16\n" +
	"\x06ChatId\x18\x02 \x01(\x05R\x06ChatId\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token\".\n" +
	"\n" +
	"RefreshRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\"L\n" +
	"\aRoleReq\x12\x1f\n" +
	"\x04role\x18\x01 \x01(\x0e2\v.types.RoleR\x04role\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\"b\n" +
	"\n" +
	"SendMsgReq\x12!\n" +
	"\fpublisher_id\x18\x01 \x01(\x05R\vpublisherId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\x05R\n" +
	"consumerId\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x82\x01\n" +
	"\n" +
	"GetRateReq\x128\n" +
	"\vcurrency_in\x18\x01 \x01(\x0e2\x17.types.ExchangeCurrencyR\n" +
	"currencyIn\x12:\n" +
	"\fcurrency_out\x18\x02 \x01(\x0e2\x17.types.ExchangeCurrencyR\vcurrencyOut\" \n" +
	"\n" +
	"GetRateRes\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x02R\x04rate\"\x87\x01\n" +
	"\x0fGetAllOrdersReq\x128\n" +
	"\vcurrency_in\x18\x01 \x01(\x0e2\x17.types.ExchangeCurrencyR\n" +
	"currencyIn\x12:\n" +
	"\fcurrency_out\x18\x02 \x01(\x0e2\x17.types.ExchangeCurrencyR\vcurrencyOut\"7\n" +
	"\x0fGetAllOrdersRes\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.types.OrderR\x06orders\"\xb9\x01\n" +
	"\x0eAddExchangeReq\x12\x1f\n" +
	"\vexchange_id\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x123\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x17.types.ExchangeCurrencyR\bcurrency\x129\n" +
	"\n" +
	"time_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStartB&Z$github.com/DEEBBLUE/ExProtos/api/Reqb\x06proto3"

var (
	file_Req_proto_rawDescOnce sync.Once
	file_Req_proto_rawDescData []byte
)

func file_Req_proto_rawDescGZIP() []byte {
	file_Req_proto_rawDescOnce.Do(func() {
		file_Req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)))
	})
	return file_Req_proto_rawDescData
}

var file_Req_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_Req_proto_goTypes = []any{
	(*DefaultRes)(nil),                // 0: req.DefaultRes
	(*EmptyReq)(nil),                  // 1: req.EmptyReq
	(*CreateUserReq)(nil),             // 2: req.CreateUserReq
	(*RepeatUserReq)(nil),             // 3: req.RepeatUserReq
	(*RepeatUserRes)(nil),             // 4: req.RepeatUserRes
	(*ChangeRoleUserReq)(nil),         // 5: req.ChangeRoleUserReq
	(*ChangeVerifeStatusUserReq)(nil), // 6: req.ChangeVerifeStatusUserReq
	(*ChangeBalanceUserReq)(nil),      // 7: req.ChangeBalanceUserReq
	(*CreateExchangeReq)(nil),         // 8: req.CreateExchangeReq
	(*CreateExchangeRes)(nil),         // 9: req.CreateExchangeRes
	(*RepeatExchangeReq)(nil),         // 10: req.RepeatExchangeReq
	(*RepeatExchangeRes)(nil),         // 11: req.RepeatExchangeRes
	(*InitBankDetailExchangeReq)(nil), // 12: req.InitBankDetailExchangeReq
	(*ConfirmReq)(nil),                // 13: req.ConfirmReq
	(*RepeatUserListReq)(nil),         // 14: req.RepeatUserListReq
	(*RepeatListExRes)(nil),           // 15: req.RepeatListExRes
	(*AccessReq)(nil),                 // 16: req.AccessReq
	(*RefreshReq)(nil),                // 17: req.RefreshReq
	(*RefreshRes)(nil),                // 18: req.RefreshRes
	(*RoleReq)(nil),                   // 19: req.RoleReq
	(*SendMsgReq)(nil),                // 20: req.SendMsgReq
	(*GetRateReq)(nil),                // 21: req.GetRateReq
	(*GetRateRes)(nil),                // 22: req.GetRateRes
	(*GetAllOrdersReq)(nil),           // 23: req.GetAllOrdersReq
	(*GetAllOrdersRes)(nil),           // 24: req.GetAllOrdersRes
	(*AddExchangeReq)(nil),            // 25: req.AddExchangeReq
	(*Types.User)(nil),                // 26: types.User
	(Types.Role)(0),                   // 27: types.Role
	(Types.Verif)(0),                  // 28: types.Verif
	(*Types.Exchange)(nil),            // 29: types.Exchange
	(Types.ExchangeCurrency)(0),       // 30: types.ExchangeCurrency
	(*Types.Order)(nil),               // 31: types.Order
	(*timestamppb.Timestamp)(nil),     // 32: google.protobuf.Timestamp
}
var file_Req_proto_depIdxs = []int32{
	26, // 0: req.RepeatUserRes.user:type_name -> types.User
	27, // 1: req.ChangeRoleUserReq.new_role:type_name -> types.Role
	28, // 2: req.ChangeVerifeStatusUserReq.new_verif:type_name -> types.Verif
	29, // 3: req.CreateExchangeReq.exchange:type_name -> types.Exchange
	29, // 4: req.RepeatExchangeRes.exchange:type_name -> types.Exchange
	29, // 5: req.RepeatListExRes.history_list:type_name -> types.Exchange
	27, // 6: req.RoleReq.role:type_name -> types.Role
	30, // 7: req.GetRateReq.currency_in:type_name -> types.ExchangeCurrency
	30, // 8: req.GetRateReq.currency_out:type_name -> types.ExchangeCurrency
	30, // 9: req.GetAllOrdersReq.currency_in:type_name -> types.ExchangeCurrency
	30, // 10: req.GetAllOrdersReq.currency_out:type_name -> types.ExchangeCurrency
	31, // 11: req.GetAllOrdersRes.orders:type_name -> types.Order
	30, // 12: req.AddExchangeReq.currency:type_name -> types.ExchangeCurrency
	32, // 13: req.AddExchangeReq.time_start:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_Req_proto_init() }
func file_Req_proto_init() {
	if File_Req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Req_proto_rawDesc), len(file_Req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Req_proto_goTypes,
		DependencyIndexes: file_Req_proto_depIdxs,
		MessageInfos:      file_Req_proto_msgTypes,
	}.Build()
	File_Req_proto = out.File
	file_Req_proto_goTypes = nil
	file_Req_proto_depIdxs = nil
}
