// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Rate.proto

package Rate

import (
	Req "github.com/DEEBBLUE/ExProtos/api/Req"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Rate_proto protoreflect.FileDescriptor

const file_Rate_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Rate.proto\x12\x04rate\x1a\tReq.proto23\n" +
	"\x04Rate\x12+\n" +
	"\aGetRate\x12\x0f.req.GetRateReq\x1a\x0f.req.GetRateResB'Z%github.com/DEEBBLUE/ExProtos/api/Rateb\x06proto3"

var file_Rate_proto_goTypes = []any{
	(*Req.GetRateReq)(nil), // 0: req.GetRateReq
	(*Req.GetRateRes)(nil), // 1: req.GetRateRes
}
var file_Rate_proto_depIdxs = []int32{
	0, // 0: rate.Rate.GetRate:input_type -> req.GetRateReq
	1, // 1: rate.Rate.GetRate:output_type -> req.GetRateRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Rate_proto_init() }
func file_Rate_proto_init() {
	if File_Rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Rate_proto_rawDesc), len(file_Rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Rate_proto_goTypes,
		DependencyIndexes: file_Rate_proto_depIdxs,
	}.Build()
	File_Rate_proto = out.File
	file_Rate_proto_goTypes = nil
	file_Rate_proto_depIdxs = nil
}
